version: '3.8'

services:
  database:
    container_name: nestjs-starter_database
    image: postgres:14.3-alpine3.15
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
